---
version: '3.1'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - ${PG_PORT}:5432
